require 'action_pack/core_ext/hash/slice'
require 'action_pack/core_ext/hash/keys'
require 'action_pack/core_ext/hash/reverse_merge'
require 'action_pack/core_ext/array/extract_options'

require 'action_pack/model_naming'
require 'action_pack/record_identifier'
require 'action_pack/form_helper/tag_helper'
require 'action_pack/form_helper/text_helper'
require 'action_pack/form_helper/form_options_helper'
require 'action_pack/form_helper/form_tag_helper'
require 'action_pack/form_helper/form_helper'
require 'action_pack/form_helper/active_model_helper'

require 'action_pack/form_helper/tags/base'
require 'action_pack/form_helper/tags/collection_helpers'
require 'action_pack/form_helper/tags/checkable'
require 'action_pack/form_helper/tags/check_box'
require 'action_pack/form_helper/tags/collection_radio_buttons'
require 'action_pack/form_helper/tags/collection_select'
require 'action_pack/form_helper/tags/grouped_collection_select'

require 'action_pack/form_helper/tags/text_field'

require 'action_pack/form_helper/tags/email_field'
require 'action_pack/form_helper/tags/file_field'
require 'action_pack/form_helper/tags/hidden_field'
require 'action_pack/form_helper/tags/label'
require 'action_pack/form_helper/tags/number_field'
require 'action_pack/form_helper/tags/password_field'
require 'action_pack/form_helper/tags/radio_button'
require 'action_pack/form_helper/tags/range_field'
require 'action_pack/form_helper/tags/select'
require 'action_pack/form_helper/tags/tel_field'
require 'action_pack/form_helper/tags/text_area'
require 'action_pack/form_helper/tags/url_field'

require 'action_pack/core'
require 'action_pack/action_syncer'
